spring.application.name=jwtSpring


spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret = ${JWT_SECRET}


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Provider 1: Google ---
# Google OAuth2 Credentials
# Standard Spring Boot OAuth2 Scopes
spring.security.oauth2.client.registration.google.client-id= ${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_CLIENT_SCOPE}

# --- Provider 2: GitHub ---
# spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_ID
# spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_SECRET
 # spring.security.oauth2.client.registration.github.scope=user:email





